### ISSUE TITLE
wistia support

### ISSUE THREAD

**Issue by punksta** [Zod-/jsVideoUrlParser#33]
Thanks for cool library. 
Please add wistia support

**Comment by Zod-** [comment]
Could you provide some example urls?
As many different as you can find like embedded, short/long urls if they
have something like that.
Is it possible to link a specific time of a video?

**Comment by punksta** [comment]
`https://appboss.wistia.com/medias/lpu6bgplle?embedType=async&videoFoam=true&videoWidth=64` (oEmbed url) 
`https://appboss.wistia.com/medias/lpu6bgplle`
`https://appboss.wistia.com/medias/lpu6bgplle?wtime=0s` (this one has time)
`https://appboss.wistia.com/medias/lpu6bgplle?embedType=async&videoWidth=640`
`https://appboss.wistia.com/medias/lpu6bgplle?embedType=iframe&videoFoam=true&videoWidth=640`
`https://appboss.wistia.com/medias/lpu6bgplle?embedType=iframe&videoWidth=640`
`https://appboss.wistia.com/medias/lpu6bgplle?embedType=iframe&seo=false&videoWidth=640`
here is examples of video share

**Comment by Zod-** [comment]
Ok seems easy enough, the all are built the same way. I'll add it in the
next few days when I have time.

On Dec 7, 2017 11:37, "Stanislav Shakirov" <notifications@github.com> wrote:

https://appboss.wistia.com/medias/lpu6bgplle?embedType=async&videoFoam=true&
videoWidth=64 (oEmbed url)
https://appboss.wistia.com/medias/lpu6bgplle
https://appboss.wistia.com/medias/lpu6bgplle?wtime=0s (this one has time)
https://appboss.wistia.com/medias/lpu6bgplle?embedType=async&videoWidth=640
https://appboss.wistia.com/medias/lpu6bgplle?embedType=
iframe&videoFoam=true&videoWidth=640
https://appboss.wistia.com/medias/lpu6bgplle?embedType=iframe&videoWidth=640
https://appboss.wistia.com/medias/lpu6bgplle?embedType=
iframe&seo=false&videoWidth=640
here is examples of video share

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Zod-/jsVideoUrlParser/issues/33#issuecomment-349929124>,
or mute the thread

**Comment by punksta** [comment]
Many thanks!

**Comment by Zod-** [comment]
So it looks like I need the channel name (appboss) to create urls, right? Unless I create embed urls like 
`https://fast.wistia.com/embed/iframe/lpu6bgplle`

**Comment by Zod-** [comment]
@punksta I've added wistia support in c833e27069be0985862b060c41c860d7a6fa711c so if you could give it a try before I release it, it would be neat.
